capital:
  total: 100000
  max_position_count: 20
  available_cash: 15014.65
  stock_available_cash: 2633.29
  fund_available_cash: 12381.36
  holdings:
  - 016874
  - '011370'
  - '010770'
  - 018147
  - 025857
  - '020105'
  - '025500'
  - 018957
  - 016186
  - '600108'
  - '518880'
  - '603156'
  watchlist:
  - '603156'
  watchlist_metadata:
    '603156':
      name: 养元饮品
      asset_type: stock
  current_positions:
  - symbol: 016874
    name: 广发远见智选混合C
    asset_type: fund_open
    cost_price: 1.382317
    shares: 9858.32
    peak_price: 1.49
    add_unlocked: false
  - symbol: '011370'
    name: 华商均衡成长混合C
    asset_type: fund_open
    cost_price: 2.193244
    shares: 1232.86
    peak_price: 2.3505
    add_unlocked: false
  - symbol: '010770'
    name: 天弘中证农业主题ETF联接C
    asset_type: fund_open
    cost_price: 0.8954
    shares: 8152.78
    peak_price: 0.9168
    add_unlocked: false
  - symbol: 018147
    name: 建信新兴市场优选混合(QDII)C
    asset_type: fund_open
    cost_price: 1.6598
    shares: 209.72
    peak_price: 1.692
    add_unlocked: false
  - symbol: 025857
    name: 华夏中证电网设备主题ETF联接C
    asset_type: fund_open
    cost_price: 1.412875
    shares: 5095.9
    peak_price: 1.4222
    add_unlocked: false
  - symbol: '020105'
    name: 易方达石油化工ETF联接C
    asset_type: fund_open
    cost_price: 1.700673
    shares: 4939.42
    peak_price: 1.692
    add_unlocked: false
  - symbol: '025500'
    name: 东方阿尔法科技智选混合C
    asset_type: fund_open
    cost_price: 1.241947
    shares: 5877.62
    peak_price: 1.2299
    add_unlocked: false
  - symbol: 018957
    name: 中航机遇领航混合C
    asset_type: fund_open
    cost_price: 3.7349
    shares: 1927.81
    peak_price: 3.6236
    add_unlocked: false
  - symbol: 016186
    name: 广发电力公用事业ETF联接C
    asset_type: fund_open
    cost_price: 1.2354
    shares: 2833.09
    peak_price: 1.2354
    add_unlocked: false
  - symbol: '600108'
    name: 亚盛集团
    asset_type: stock
    cost_price: 6.3075
    shares: 400
    peak_price: 6.96
    add_unlocked: true
  - symbol: '518880'
    name: 黄金ETF
    asset_type: etf
    cost_price: 11.331
    shares: 100
    peak_price: 10.938
    add_unlocked: false
  - symbol: '603156'
    name: 养元饮品
    asset_type: stock
    cost_price: 30.97
    shares: 100
    peak_price: 30.97
    add_unlocked: false
livermore:
  asset_params:
    stock:
      m: 0.05
      c: 0.05
      h: 0.08
      k: 0.3
    etf:
      m: 0.05
      c: 0.05
      h: 0.08
      k: 0.3
    fund_open:
      m: 0.05
      c: 0.07
      h: 0.08
      k: 0.7
signal:
  min_volume_ratio: 0.8
  scan_etf_top_n: 8
  scan_stock_top_n: 8
  scan_eval_days: 365
  asset_params: {}
portfolio:
  method: equal_weight
  rebalance_freq: monthly
evaluation:
  risk_free_rate: 0.02
  benchmark: '000300'
